services:
  - type: web
    name: todays-meal
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    env: python
    plan: free
    region: oregon
    branch: main
